#!/usr/bin/env python3
import os
import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
# The repo memory says "Python tooling scripts must avoid external dependencies (e.g., PyYAML) and rely on the standard library for parsing the 'YAML-light' subset."
# We will write a lightweight manual parser for this specific file format.

OUTPUT_FILE = 'docs/_generated/impl-index.md'
REGISTRY_PATH = 'audit/impl-registry.yaml'

def load_registry(path):
    if not os.path.exists(path):
        return None

    # Very simple manual parser tailored for the impl-registry.yaml format
    data = {'implementations': []}
    current_impl = None
    current_list_key = None

    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith('#'):
                continue

            if line.startswith('implementations:'):
                continue

            if line.startswith('  - id:'):
                if current_impl is not None:
                    data['implementations'].append(current_impl)
                current_impl = {'id': stripped.split(':', 1)[1].strip()}
                current_list_key = None
            elif current_impl is not None and line.startswith('    ') and ':' in stripped:
                key, val = stripped.split(':', 1)
                key = key.strip()
                val = val.strip()

                if val == '[]' or not val:
                    current_impl[key] = []
                    current_list_key = key
                elif val.startswith('[') and val.endswith(']'):
                    pass # inline list handled simply
                else:
                    current_impl[key] = val
                    current_list_key = None
            elif current_impl is not None and line.startswith('      - ') and current_list_key:
                val = stripped[2:].strip()
                current_impl[current_list_key].append(val)

    if current_impl is not None:
         data['implementations'].append(current_impl)

    return data

def generate_impl_index(registry_data):
    lines = [
        "# Critical Implementations Registry",
        f"**Source:** `{REGISTRY_PATH}`\n",
        "⛔️ **DO NOT EDIT THIS FILE MANUALLY** ⛔️\n"
    ]

    if not registry_data or 'implementations' not in registry_data:
        lines.append("_No implementations registered._")
        return "\n".join(lines) + "\n"

    lines.append("| ID | Type | Path | Status | Documented By | Verified By |")
    lines.append("|---|---|---|---|---|---|")

    for impl in registry_data['implementations']:
        impl_id = impl.get('id', 'N/A')
        impl_type = impl.get('impl_type', 'N/A')
        path = impl.get('path', 'N/A')
        status = impl.get('status', 'N/A')

        doc_by = impl.get('documented_by', [])
        ver_by = impl.get('verified_by', [])

        doc_str = ", ".join([f"`{d}`" for d in doc_by]) if doc_by else "-"
        ver_str = ", ".join([f"`{v}`" for v in ver_by]) if ver_by else "-"

        lines.append(f"| `{impl_id}` | {impl_type} | `{path}` | {status} | {doc_str} | {ver_str} |")

    return "\n".join(lines) + "\n"

def main():
    try:
        data = load_registry(REGISTRY_PATH)
        content = generate_impl_index(data)

        os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(content)

        print(f"Successfully generated {OUTPUT_FILE}")
    except Exception as e:
        print(f"Error generating implementation index: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
