#!/usr/bin/env python3
import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from scripts.lib.docmeta import load_repo_index, MANIFEST_PATH

OUTPUT_FILE = 'docs/_generated/orphans.md'

# Directories to scan for markdown files
SCAN_DIRS = ['architecture', 'operations', 'runbooks', 'runtime', 'docs']

def get_manifest_docs(manifest):
    docs = set()
    zones = manifest.get('zones', {})
    for zone in zones.values():
        path = zone.get('path', '')
        for doc in zone.get('canonical_docs', []):
            docs.add(os.path.join(path, doc))
    return docs

def find_markdown_files():
    md_files = set()
    for scan_dir in SCAN_DIRS:
        if not os.path.exists(scan_dir):
            continue
        for root, _, files in os.walk(scan_dir):
            if '_generated' in root:
                continue # Skip generated files
            for file in files:
                if file.endswith('.md'):
                    md_files.add(os.path.join(root, file))

    # Also add root files
    if os.path.exists('README.md'): md_files.add('README.md')
    if os.path.exists('AGENTS.md'): md_files.add('AGENTS.md')
    return md_files

def main():
    try:
        manifest = load_repo_index(MANIFEST_PATH)
        manifest_docs = get_manifest_docs(manifest)

        # Add index.md which is canonically listed in repo.meta.yaml, not repo-index.yaml typically
        manifest_docs.add('docs/index.md')
        manifest_docs.add('README.md')
        manifest_docs.add('AGENTS.md')

        all_md_files = find_markdown_files()

        orphans = all_md_files - manifest_docs

        lines = [
            "# Orphans Report",
            "**Source:** Discovery scan vs `manifest/repo-index.yaml`.\n",
            "⛔️ **DO NOT EDIT THIS FILE MANUALLY** ⛔️\n",
            "The following markdown files are not listed in the canonical documentation manifest or designated as safe root files:\n"
        ]

        if not orphans:
            lines.append("_No orphans found!_\n")
        else:
            lines.append("| Orphan File |")
            lines.append("|---|")
            for orphan in sorted(orphans):
                lines.append(f"| `../../{orphan}` |")

        content = "\n".join(lines) + "\n"

        os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(content)

        print(f"Successfully generated {OUTPUT_FILE}")

    except Exception as e:
        print(f"Error generating orphans report: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
