#!/usr/bin/env python3
import os
import sys

# Ensure we can import from scripts/lib
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from scripts.lib.docmeta import load_repo_index, parse_frontmatter, MANIFEST_PATH

OUTPUT_FILE = 'docs/_generated/doc-index.md'

def generate_doc_index(manifest):
    lines = []
    lines.append("# Generated Document Index")
    lines.append("**Source:** `manifest/repo-index.yaml` and discovered `.md` files.\n")
    lines.append("⛔️ **DO NOT EDIT THIS FILE MANUALLY** ⛔️\n")

    lines.append("| Title | ID | Role | Status | Path | Links |")
    lines.append("|---|---|---|---|---|---|")

    zones = manifest.get('zones', {})

    for zone_name, zone_data in zones.items():
        base_path = zone_data.get('path', '')
        docs = zone_data.get('canonical_docs', [])

        for doc in docs:
            filepath = os.path.join(base_path, doc)
            fm = parse_frontmatter(filepath)

            if fm:
                title = fm.get('id', filepath) # fallback to filepath if title missing
                doc_id = fm.get('id', 'N/A')
                role = fm.get('role', 'N/A')
                status = fm.get('status', 'N/A')
                links = fm.get('depends_on', [])

                links_str = ", ".join(links) if isinstance(links, list) else str(links)
                if not links_str:
                    links_str = "-"

                # relative link from docs/_generated
                rel_path = f"../../{filepath}"
                lines.append(f"| [{title}]({rel_path}) | `{doc_id}` | {role} | {status} | `{filepath}` | {links_str} |")
            else:
                rel_path = f"../../{filepath}"
                lines.append(f"| [{filepath}]({rel_path}) | ❌ Error | - | - | `{filepath}` | - |")

    content = "\n".join(lines) + "\n"
    return content

def main():
    if not os.path.exists(MANIFEST_PATH):
        print(f"Error: Manifest not found at {MANIFEST_PATH}")
        sys.exit(1)

    try:
        manifest = load_repo_index(MANIFEST_PATH)
        content = generate_doc_index(manifest)

        os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(content)

        print(f"Successfully generated {OUTPUT_FILE}")
    except Exception as e:
        print(f"Error generating doc index: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
