#!/usr/bin/env bash
set -euo pipefail

# Generated Files Guard
# Checks that generated files contain an auto-generated header

log() { printf "INFO: %s\n" "$*"; }
fail() { printf "FAIL: %s\n" "$*" >&2; exit 1; }

# Function to check if a file has an auto-generated marker
check_generated_marker() {
    local file=$1
    if ! grep -iE -q "automatically generated|do not edit|generated by" "$file"; then
        fail "Generated file $file is missing an auto-generated header marker."
    fi
}

# 1. Check SYSTEM_MAP.md
if [ -f "SYSTEM_MAP.md" ]; then
    check_generated_marker "SYSTEM_MAP.md"
fi

# 2. Check files in docs/_generated/
if [ -d "docs/_generated" ]; then
    for file in docs/_generated/*.md; do
        if [ -f "$file" ]; then
            check_generated_marker "$file"
        fi
    done
fi

log "Generated files checks passed."
