#!/usr/bin/env python3
import os
import sys
import json

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts.lib.docmeta import load_repo_index, parse_frontmatter, MANIFEST_PATH

def get_discovery_roots():
    roots = []
    if os.path.exists('repo.meta.yaml'):
        with open('repo.meta.yaml', 'r', encoding='utf-8') as f:
            lines = f.readlines()
        in_roots = False
        for line in lines:
            if line.startswith('discovery_roots:'):
                in_roots = True
                continue
            if in_roots and line.startswith('  - '):
                roots.append(line.strip()[2:].strip())
            elif in_roots and line.strip() and not line.startswith(' '):
                in_roots = False
    return roots

def find_all_markdown_files(roots):
    found = []
    for root in roots:
        # Avoid traversing into generated files
        if '_generated' in root: continue

        # If root is a file, just add it if it's md
        if os.path.isfile(root) and root.endswith('.md'):
            found.append(root)
            continue

        # If root is a dir, walk it
        if os.path.isdir(root):
            for dirpath, _, filenames in os.walk(root):
                if '_generated' in dirpath: continue
                for filename in filenames:
                    if filename.endswith('.md'):
                        # Normalize path
                        path = os.path.join(dirpath, filename).replace('\\', '/')
                        found.append(path)
    return set(found)

def generate_relations():
    if not os.path.exists(MANIFEST_PATH):
        print(f"Error: Manifest not found at {MANIFEST_PATH}")
        sys.exit(1)

    manifest = load_repo_index(MANIFEST_PATH)
    zones = manifest.get('zones', {})

    docs_by_id = {}
    docs_metadata = {}
    canonical_filepaths = set()

    # 1. Collect all canonical documents and parse their frontmatter
    for zone_name, zone_data in zones.items():
        base_path = zone_data.get('path', '')
        canonical_docs = zone_data.get('canonical_docs', [])

        for doc in canonical_docs:
            filepath = os.path.join(base_path, doc).replace('\\', '/')
            canonical_filepaths.add(filepath)
            fm = parse_frontmatter(filepath)
            if fm:
                doc_id = fm.get('id')
                if doc_id:
                    docs_by_id[doc_id] = filepath
                    docs_metadata[doc_id] = {
                        'filepath': filepath,
                        'zone': zone_name,
                        'depends_on': fm.get('depends_on', []),
                        'title': fm.get('title', 'Unknown Title'),
                        'doc_type': fm.get('doc_type', 'Unknown'),
                        'status': fm.get('status', 'Unknown'),
                        'canonicality': fm.get('canonicality', 'Unknown'),
                        'supersedes': fm.get('supersedes', []),
                        'deprecated_by': fm.get('deprecated_by', [])
                    }

    # 1b. True Discovery
    discovery_roots = get_discovery_roots()
    discovered_files = find_all_markdown_files(discovery_roots)

    orphans = list(discovered_files - canonical_filepaths)

    relations = {
        'nodes': [],
        'edges': []
    }

    backlinks = {doc_id: [] for doc_id in docs_by_id.keys()}

    # 2. Build graph edges and calculate backlinks
    for doc_id, meta in docs_metadata.items():
        relations['nodes'].append({
            'id': doc_id,
            'path': meta['filepath'],
            'zone': meta['zone']
        })

        deps = meta['depends_on']
        if isinstance(deps, str):
            deps = [deps]
        if not deps:
            deps = []

        has_outgoing = False

        for dep in deps:
            target_id = None
            if dep in docs_by_id:
                target_id = dep
            else:
                # Try to resolve filename matches to ids
                for k, v in docs_by_id.items():
                    if v.endswith(dep) or v == dep:
                        target_id = k
                        break

            if target_id:
                has_outgoing = True
                relations['edges'].append({
                    'source': doc_id,
                    'target': target_id,
                    'type': 'depends_on'
                })
                if doc_id not in backlinks[target_id]:
                    backlinks[target_id].append(doc_id)

    # 3. Generate Doc Index
    os.makedirs('docs/_generated', exist_ok=True)
    with open('docs/_generated/doc-index.md', 'w', encoding='utf-8') as f:
        f.write("# Canonical Document Index\n\n")
        f.write("This file is automatically generated by `scripts/generate-relations.py` and lists all mapped canonical documents.\n\n")
        f.write("| Title | Type | Status | Canonicality | Path |\n")
        f.write("|---|---|---|---|---|\n")
        for doc_id, meta in sorted(docs_metadata.items(), key=lambda x: x[1]['title']):
            f.write(f"| {meta['title']} | {meta['doc_type']} | {meta['status']} | {meta['canonicality']} | `{meta['filepath']}` |\n")

    # 4. Generate JSON artifact
    os.makedirs('docs/_generated', exist_ok=True)
    with open('docs/_generated/relations.json', 'w', encoding='utf-8') as f:
        json.dump(relations, f, indent=2)

    # 5. Generate Backlinks Markdown
    with open('docs/_generated/backlinks.md', 'w', encoding='utf-8') as f:
        f.write("# Backlinks Report\n\n")
        f.write("This file is automatically generated by `scripts/generate-relations.py`. It shows which documents depend on a given document.\n\n")

        for doc_id in sorted(backlinks.keys()):
            links = backlinks[doc_id]
            f.write(f"## `{doc_id}`\n")
            if links:
                for link in sorted(links):
                    f.write(f"- `{link}`\n")
            else:
                f.write("_No incoming links._\n")
            f.write("\n")

    # 6. Generate Orphans Markdown
    with open('docs/_generated/orphans.md', 'w', encoding='utf-8') as f:
        f.write("# Orphaned Documents Report\n\n")
        f.write("This file is automatically generated by `scripts/generate-relations.py`. It lists `.md` files found in the discovery roots that are not mapped in `manifest/repo-index.yaml`.\n\n")

        if orphans:
            for orphan in sorted(orphans):
                f.write(f"- `{orphan}`\n")
        else:
            f.write("_No unmapped orphaned documents found!_\n")

    # 7. Generate implementation index and supersession map
    impl_registry_path = 'audit/impl-registry.yaml'
    if os.path.exists(impl_registry_path):
        try:
            # Very basic manual YAML parsing to avoid PyYAML dependency as per project rules
            with open(impl_registry_path, 'r', encoding='utf-8') as f:
                content = f.read()

            implementations = []
            current_impl = {}
            in_documented_by = False
            in_supersedes = False
            in_deprecated_by = False

            for line in content.splitlines():
                stripped = line.strip()
                if stripped.startswith('- id:'):
                    if current_impl:
                        implementations.append(current_impl)
                    current_impl = {'id': stripped.split(':', 1)[1].strip(), 'documented_by': [], 'supersedes': [], 'deprecated_by': []}
                    in_documented_by = False
                    in_supersedes = False
                    in_deprecated_by = False
                elif stripped.startswith('path:'):
                    current_impl['path'] = stripped.split(':', 1)[1].strip()
                    in_documented_by = False
                elif stripped.startswith('impl_type:'):
                    current_impl['impl_type'] = stripped.split(':', 1)[1].strip()
                    in_documented_by = False
                elif stripped.startswith('status:'):
                    current_impl['status'] = stripped.split(':', 1)[1].strip()
                    in_documented_by = False
                elif stripped.startswith('documented_by:'):
                    in_documented_by = True
                    in_supersedes = False
                    in_deprecated_by = False
                elif stripped.startswith('supersedes:'):
                    in_supersedes = True
                    in_documented_by = False
                    in_deprecated_by = False
                elif stripped.startswith('deprecated_by:'):
                    in_deprecated_by = True
                    in_documented_by = False
                    in_supersedes = False
                elif in_documented_by and stripped.startswith('- '):
                    current_impl['documented_by'].append(stripped[2:].strip())
                elif in_supersedes and stripped.startswith('- '):
                    current_impl['supersedes'].append(stripped[2:].strip())
                elif in_deprecated_by and stripped.startswith('- '):
                    current_impl['deprecated_by'].append(stripped[2:].strip())
                elif stripped and not stripped.startswith('- '):
                    in_documented_by = False
                    in_supersedes = False
                    in_deprecated_by = False

            if current_impl:
                implementations.append(current_impl)

            if implementations:
                 with open('docs/_generated/impl-index.md', 'w', encoding='utf-8') as f:
                     f.write("# Critical Implementations Index\n\n")
                     f.write("This file is automatically generated by `scripts/generate-relations.py` from `audit/impl-registry.yaml`.\n\n")
                     f.write("| ID | Type | Path | Status | Documented By |\n")
                     f.write("|---|---|---|---|---|\n")
                     for impl in implementations:
                         docs = impl.get('documented_by', [])
                         docs_str = ", ".join([f"`{d}`" for d in docs]) if docs else "-"
                         f.write(f"| `{impl.get('id', '')}` | {impl.get('impl_type', '')} | `{impl.get('path', '')}` | {impl.get('status', '')} | {docs_str} |\n")
                 print("Successfully generated docs/_generated/impl-index.md")
        except Exception as e:
             print(f"Warning: Could not parse impl-registry.yaml: {e}")

    # 8. Generate basic supersession map
    has_supersessions = False
    supersession_lines = []

    # Check documents
    for doc_id, meta in docs_metadata.items():
        supersedes = meta.get('supersedes', [])
        deprecated_by = meta.get('deprecated_by', [])

        if isinstance(supersedes, str): supersedes = [supersedes]
        if isinstance(deprecated_by, str): deprecated_by = [deprecated_by]

        if supersedes or deprecated_by:
            has_supersessions = True
            supersession_lines.append(f"### Document: `{doc_id}`")
            if supersedes:
                supersession_lines.append(f"- **Supersedes:** {', '.join(['`' + s + '`' for s in supersedes])}")
            if deprecated_by:
                supersession_lines.append(f"- **Deprecated By:** {', '.join(['`' + d + '`' for d in deprecated_by])}")
            supersession_lines.append("")

    # Check implementations
    if 'implementations' in locals():
        for impl in implementations:
            supersedes = impl.get('supersedes', [])
            deprecated_by = impl.get('deprecated_by', [])

            if isinstance(supersedes, str): supersedes = [supersedes]
            if isinstance(deprecated_by, str): deprecated_by = [deprecated_by]

            if supersedes or deprecated_by:
                has_supersessions = True
                supersession_lines.append(f"### Implementation: `{impl.get('id', 'unknown')}`")
                if supersedes:
                    supersession_lines.append(f"- **Supersedes:** {', '.join(['`' + s + '`' for s in supersedes])}")
                if deprecated_by:
                    supersession_lines.append(f"- **Deprecated By:** {', '.join(['`' + d + '`' for d in deprecated_by])}")
                supersession_lines.append("")

    with open('docs/_generated/supersession-map.md', 'w', encoding='utf-8') as f:
        f.write("# Supersession Map\n\n")
        f.write("This file is automatically generated by `scripts/generate-relations.py` and tracks deprecated and superseded documents and implementations.\n\n")
        if has_supersessions:
            f.write("\n".join(supersession_lines))
        else:
            f.write("_No supersessions found._\n")

    print("Successfully generated docs/_generated/relations.json")
    print("Successfully generated docs/_generated/backlinks.md")
    print("Successfully generated docs/_generated/orphans.md")
    print("Successfully generated docs/_generated/supersession-map.md")

if __name__ == '__main__':
    generate_relations()
