#!/usr/bin/env python3
import os
import sys
import posixpath

# Ensure we can import from scripts/lib
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts.lib.docmeta import load_repo_index, parse_frontmatter, MANIFEST_PATH

OUTPUT_FILE = 'SYSTEM_MAP.md'

def generate_system_map(manifest):
    lines = []
    lines.append("# Heimserver System Map")
    # Timestamp removed for determinism
    lines.append("**Source:** `manifest/repo-index.yaml`")
    lines.append("\n⛔️ **DO NOT EDIT THIS FILE MANUALLY** ⛔️\n")

    zones = manifest.get('zones', {})

    # Preferred display order for known zones; any zone not in this list is
    # appended afterwards in stable (insertion) order so new zones are never
    # silently dropped from the map.
    preferred_zone_order = ['norm', 'reality', 'action', 'runbooks', 'decisions', 'docs']
    extra_zones = [z for z in zones if z not in preferred_zone_order]
    zone_order = preferred_zone_order + extra_zones

    for zone_key in zone_order:
        if zone_key not in zones:
            continue

        zone = zones[zone_key]
        path_prefix = zone.get('path', '')
        canonical_docs = zone.get('canonical_docs', [])

        lines.append(f"## Zone: {zone_key.upper()}")
        lines.append(f"**Path:** `{path_prefix}`\n")

        if not canonical_docs:
            lines.append("_No documents listed._\n")
            continue

        lines.append("| Document | ID | Doc Role | Status | Reviewed | Verifies With |")
        lines.append("|---|---|---|---|---|---|")

        for doc in canonical_docs:
            # Use os.path.join for file system check
            filepath = os.path.join(path_prefix, doc)

            # Use posixpath for markdown link (always forward slashes)
            clean_prefix = path_prefix.rstrip('/')
            link_path = posixpath.join(clean_prefix, doc)

            fm = parse_frontmatter(filepath)

            if fm:
                doc_id = fm.get('id', 'N/A')
                doc_role = fm.get('doc_role', '-')
                status = fm.get('status', 'N/A')
                reviewed = fm.get('last_reviewed', 'N/A')
                verifies = fm.get('verifies_with', [])

                if isinstance(verifies, list):
                    verifies_str = ", ".join([f"`{v}`" for v in verifies])
                elif isinstance(verifies, str):
                    verifies_str = f"`{verifies}`"
                else:
                    verifies_str = "-"

                if not verifies_str:
                    verifies_str = "-"

                file_link = f"[{doc}]({link_path})"

                lines.append(f"| {file_link} | `{doc_id}` | {doc_role} | {status} | {reviewed} | {verifies_str} |")
            else:
                 lines.append(f"| [{doc}]({link_path}) | ❌ Parse Error | N/A | N/A | N/A | N/A |")

        lines.append("")

    lines.append("## Dependencies")

    deps_list = []
    for zone_key in zone_order:
        if zone_key not in zones:
            continue
        zone = zones[zone_key]
        path_prefix = zone.get('path', '')
        canonical_docs = zone.get('canonical_docs', [])

        for doc in canonical_docs:
            filepath = os.path.join(path_prefix, doc)
            fm = parse_frontmatter(filepath)
            if fm and fm.get('depends_on'):
                deps = fm.get('depends_on')

                if isinstance(deps, str):
                    deps = [deps]

                if deps:
                    deps_str = ", ".join([f"`{d}`" for d in deps])
                    deps_list.append(f"- **{doc}** depends on: {deps_str}")

    if deps_list:
        lines.append("Documents that depend on others:\n")
        lines.extend(deps_list)
    else:
        lines.append("_No explicit dependencies declared._")
    lines.append("")

    lines.append("## Automated Checks")
    checks = manifest.get('checks', [])
    if checks:
        for check in checks:
            # Check implies check path is relative to root
            lines.append(f"- [`{check}`]({check})")
    else:
        lines.append("_No checks listed._")

    content = "\n".join(lines)
    if not content.endswith('\n'):
        content += '\n'
    return content

def main():
    if not os.path.exists(MANIFEST_PATH):
        print(f"Error: Manifest not found at {MANIFEST_PATH}")
        sys.exit(1)

    try:
        manifest = load_repo_index(MANIFEST_PATH)
        content = generate_system_map(manifest)

        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(content)

        print(f"Successfully generated {OUTPUT_FILE}")
    except Exception as e:
        print(f"Error generating system map: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
