#!/usr/bin/env python3
import os
import re
import sys
from datetime import datetime

MANIFEST_PATH = 'manifest/repo-index.yaml'
OUTPUT_FILE = 'SYSTEM_MAP.md'

def load_manifest():
    data = {'zones': {}, 'checks': []}
    current_zone = None
    in_checks = False

    with open(MANIFEST_PATH, 'r') as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith('#'):
                continue

            if stripped == 'zones:':
                in_checks = False
                continue
            elif stripped == 'checks:':
                in_checks = True
                continue

            if in_checks:
                if stripped.startswith('- '):
                    data['checks'].append(stripped[2:])
            else:
                # In zones
                # Check for zone definition: "  norm:" (2 spaces)
                if line.startswith('  ') and not line.startswith('    ') and stripped.endswith(':'):
                    zone_name = stripped[:-1]
                    current_zone = zone_name
                    data['zones'][current_zone] = {'path': '', 'canonical_docs': []}

                # Check for path: "    path: ..." (4 spaces)
                elif line.startswith('    path:'):
                    path = stripped.split(':', 1)[1].strip()
                    if current_zone:
                        data['zones'][current_zone]['path'] = path

                # Check for canonical_docs list start
                elif line.startswith('    canonical_docs:'):
                    pass # Just a header

                # Check for list items: "      - ..." (6 spaces)
                elif line.startswith('      - '):
                    doc = stripped[2:]
                    if current_zone:
                        data['zones'][current_zone]['canonical_docs'].append(doc)

    return data

def parse_frontmatter(filepath):
    if not os.path.exists(filepath):
        return None

    with open(filepath, 'r') as f:
        content = f.read()

    match = re.match(r'^---\n(.*?)\n---', content, re.DOTALL)
    if not match:
        return None

    fm_content = match.group(1)
    data = {}
    current_list_key = None

    for line in fm_content.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith('#'):
            continue

        # Check if line is a list item
        if stripped.startswith('- '):
            if current_list_key:
                val = stripped[2:].strip()
                # If val is quoted, unquote
                if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
                    val = val[1:-1]
                data[current_list_key].append(val)
            continue

        if ':' in stripped:
            key, val = stripped.split(':', 1)
            key = key.strip()
            val = val.strip()

            if not val:
                current_list_key = key
                data[key] = []
            elif val.startswith('[') and val.endswith(']'):
                # Inline list
                if val == '[]':
                     data[key] = []
                else:
                     items = [x.strip() for x in val[1:-1].split(',')]
                     # remove quotes
                     clean_items = []
                     for item in items:
                         if (item.startswith('"') and item.endswith('"')) or (item.startswith("'") and item.endswith("'")):
                             clean_items.append(item[1:-1])
                         else:
                             clean_items.append(item)
                     data[key] = clean_items
                current_list_key = None
            else:
                # Plain value
                if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
                    val = val[1:-1]
                data[key] = val
                current_list_key = None

    return data

def generate_system_map(manifest):
    lines = []
    lines.append("# Heimserver System Map")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("**Source:** `manifest/repo-index.yaml`")
    lines.append("\n⛔️ **DO NOT EDIT THIS FILE MANUALLY** ⛔️\n")

    zones = manifest.get('zones', {})

    # Define order
    zone_order = ['norm', 'reality', 'action', 'runbooks']

    for zone_key in zone_order:
        if zone_key not in zones:
            continue

        zone = zones[zone_key]
        path_prefix = zone.get('path', '')
        canonical_docs = zone.get('canonical_docs', [])

        lines.append(f"## Zone: {zone_key.upper()}")
        lines.append(f"**Path:** `{path_prefix}`\n")

        if not canonical_docs:
            lines.append("_No documents listed._\n")
            continue

        lines.append("| Document | ID | Status | Reviewed | Verifies With |")
        lines.append("|---|---|---|---|---|")

        for doc in canonical_docs:
            filepath = os.path.join(path_prefix, doc)
            fm = parse_frontmatter(filepath)

            if fm:
                doc_id = fm.get('id', 'N/A')
                status = fm.get('status', 'N/A')
                reviewed = fm.get('last_reviewed', 'N/A')
                verifies = fm.get('verifies_with', [])

                if isinstance(verifies, list):
                    verifies_str = ", ".join([f"`{v}`" for v in verifies])
                elif isinstance(verifies, str):
                    verifies_str = f"`{verifies}`"
                else:
                    verifies_str = "-"

                if not verifies_str:
                    verifies_str = "-"

                # Make file path a link relative to repo root
                file_link = f"[{doc}]({filepath})"

                lines.append(f"| {file_link} | `{doc_id}` | {status} | {reviewed} | {verifies_str} |")
            else:
                 lines.append(f"| [{doc}]({filepath}) | ❌ Error | - | - | - |")

        lines.append("")

    lines.append("## Dependencies")

    deps_list = []
    for zone_key in zone_order:
        if zone_key not in zones:
            continue
        zone = zones[zone_key]
        path_prefix = zone.get('path', '')
        canonical_docs = zone.get('canonical_docs', [])

        for doc in canonical_docs:
            filepath = os.path.join(path_prefix, doc)
            fm = parse_frontmatter(filepath)
            if fm and fm.get('depends_on'):
                deps = fm.get('depends_on')
                if isinstance(deps, list) and deps:
                    deps_str = ", ".join([f"`{d}`" for d in deps])
                    deps_list.append(f"- **{doc}** depends on: {deps_str}")

    if deps_list:
        lines.append("Documents that depend on others:\n")
        lines.extend(deps_list)
    else:
        lines.append("_No explicit dependencies declared._")
    lines.append("")

    lines.append("## Automated Checks")
    checks = manifest.get('checks', [])
    if checks:
        for check in checks:
            lines.append(f"- [`{check}`]({check})")
    else:
        lines.append("_No checks listed._")

    return "\n".join(lines)

def main():
    if not os.path.exists(MANIFEST_PATH):
        print(f"Error: Manifest not found at {MANIFEST_PATH}")
        sys.exit(1)

    try:
        manifest = load_manifest()
        content = generate_system_map(manifest)

        with open(OUTPUT_FILE, 'w') as f:
            f.write(content)

        print(f"Successfully generated {OUTPUT_FILE}")
    except Exception as e:
        print(f"Error generating system map: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
