#!/usr/bin/env python3
import os
import sys
import json

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts.lib.docmeta import load_repo_index, parse_frontmatter, MANIFEST_PATH

def generate_relations():
    if not os.path.exists(MANIFEST_PATH):
        print(f"Error: Manifest not found at {MANIFEST_PATH}")
        sys.exit(1)

    manifest = load_repo_index(MANIFEST_PATH)
    zones = manifest.get('zones', {})

    docs_by_id = {}
    docs_metadata = {}

    # 1. Collect all canonical documents and parse their frontmatter
    for zone_name, zone_data in zones.items():
        base_path = zone_data.get('path', '')
        canonical_docs = zone_data.get('canonical_docs', [])

        for doc in canonical_docs:
            filepath = os.path.join(base_path, doc)
            fm = parse_frontmatter(filepath)
            if fm:
                doc_id = fm.get('id')
                if doc_id:
                    docs_by_id[doc_id] = filepath
                    docs_metadata[doc_id] = {
                        'filepath': filepath,
                        'zone': zone_name,
                        'depends_on': fm.get('depends_on', [])
                    }

    relations = {
        'nodes': [],
        'edges': []
    }

    backlinks = {doc_id: [] for doc_id in docs_by_id.keys()}
    orphans = []

    # 2. Build graph edges and calculate backlinks
    for doc_id, meta in docs_metadata.items():
        relations['nodes'].append({
            'id': doc_id,
            'path': meta['filepath'],
            'zone': meta['zone']
        })

        deps = meta['depends_on']
        if isinstance(deps, str):
            deps = [deps]
        if not deps:
            deps = []

        has_outgoing = False

        for dep in deps:
            target_id = None
            if dep in docs_by_id:
                target_id = dep
            else:
                # Try to resolve filename matches to ids
                for k, v in docs_by_id.items():
                    if v.endswith(dep) or v == dep:
                        target_id = k
                        break

            if target_id:
                has_outgoing = True
                relations['edges'].append({
                    'source': doc_id,
                    'target': target_id,
                    'type': 'depends_on'
                })
                if doc_id not in backlinks[target_id]:
                    backlinks[target_id].append(doc_id)

    # 3. Find orphans (no outgoing and no incoming)
    for doc_id in docs_by_id.keys():
        has_incoming = len(backlinks[doc_id]) > 0
        has_outgoing = any(edge['source'] == doc_id for edge in relations['edges'])
        if not has_incoming and not has_outgoing:
            orphans.append(doc_id)

    # 4. Generate JSON artifact
    os.makedirs('docs/_generated', exist_ok=True)
    with open('docs/_generated/relations.json', 'w', encoding='utf-8') as f:
        json.dump(relations, f, indent=2)

    # 5. Generate Backlinks Markdown
    with open('docs/_generated/backlinks.md', 'w', encoding='utf-8') as f:
        f.write("# Backlinks Report\n\n")
        f.write("This file is automatically generated. It shows which documents depend on a given document.\n\n")

        for doc_id in sorted(backlinks.keys()):
            links = backlinks[doc_id]
            f.write(f"## `{doc_id}`\n")
            if links:
                for link in sorted(links):
                    f.write(f"- `{link}`\n")
            else:
                f.write("_No incoming links._\n")
            f.write("\n")

    # 6. Generate Orphans Markdown
    with open('docs/_generated/orphans.md', 'w', encoding='utf-8') as f:
        f.write("# Orphaned Documents Report\n\n")
        f.write("This file is automatically generated. It lists canonical documents that have no dependencies and are not depended upon by any other document.\n\n")

        if orphans:
            for orphan in sorted(orphans):
                filepath = docs_metadata[orphan]['filepath']
                f.write(f"- `{orphan}` ({filepath})\n")
        else:
            f.write("_No orphaned documents found!_\n")

    # 7. Generate implementation index and supersession map
    impl_registry_path = 'audit/impl-registry.yaml'
    if os.path.exists(impl_registry_path):
        try:
            # Very basic manual YAML parsing to avoid PyYAML dependency as per project rules
            with open(impl_registry_path, 'r', encoding='utf-8') as f:
                content = f.read()

            implementations = []
            current_impl = {}
            in_documented_by = False

            for line in content.splitlines():
                stripped = line.strip()
                if stripped.startswith('- id:'):
                    if current_impl:
                        implementations.append(current_impl)
                    current_impl = {'id': stripped.split(':', 1)[1].strip(), 'documented_by': []}
                    in_documented_by = False
                elif stripped.startswith('path:'):
                    current_impl['path'] = stripped.split(':', 1)[1].strip()
                    in_documented_by = False
                elif stripped.startswith('impl_type:'):
                    current_impl['impl_type'] = stripped.split(':', 1)[1].strip()
                    in_documented_by = False
                elif stripped.startswith('status:'):
                    current_impl['status'] = stripped.split(':', 1)[1].strip()
                    in_documented_by = False
                elif stripped.startswith('documented_by:'):
                    in_documented_by = True
                elif in_documented_by and stripped.startswith('- '):
                    current_impl['documented_by'].append(stripped[2:].strip())
                elif stripped and not stripped.startswith('- '):
                    in_documented_by = False

            if current_impl:
                implementations.append(current_impl)

            if implementations:
                 with open('docs/_generated/impl-index.md', 'w', encoding='utf-8') as f:
                     f.write("# Critical Implementations Index\n\n")
                     f.write("This file is automatically generated from `audit/impl-registry.yaml`.\n\n")
                     f.write("| ID | Type | Path | Status | Documented By |\n")
                     f.write("|---|---|---|---|---|\n")
                     for impl in implementations:
                         docs = impl.get('documented_by', [])
                         docs_str = ", ".join([f"`{d}`" for d in docs]) if docs else "-"
                         f.write(f"| `{impl.get('id', '')}` | {impl.get('impl_type', '')} | `{impl.get('path', '')}` | {impl.get('status', '')} | {docs_str} |\n")
                 print("Successfully generated docs/_generated/impl-index.md")
        except Exception as e:
             print(f"Warning: Could not parse impl-registry.yaml: {e}")

    # Generate basic supersession map if needed
    with open('docs/_generated/supersession-map.md', 'w', encoding='utf-8') as f:
        f.write("# Supersession Map\n\n")
        f.write("This file tracks deprecated and superseded documents.\n\n")
        f.write("_No supersessions found._\n")

    print("Successfully generated docs/_generated/relations.json")
    print("Successfully generated docs/_generated/backlinks.md")
    print("Successfully generated docs/_generated/orphans.md")
    print("Successfully generated docs/_generated/supersession-map.md")

if __name__ == '__main__':
    generate_relations()
